### ISSUE TITLE
get can't use wildcards as we have no issue where the data is from

### ISSUE THREAD

**Issue by JohanvdWest** [happner/happn#18]
Subscribing to data passes the meta so that you know where data comes from.

Getting data just gives an array of values, which is not usable.  We need the metadata in the get as well.

This was working before the _meta change and we've built components around this.

**Comment by southbite** [comment]
is this still an issue - you should get passed back a _meta property for each of your items

**Comment by JohanvdWest** [comment]
No longer an issue, can close.
