### ISSUE TITLE
Setting data with merge true can override data

### ISSUE THREAD

**Issue by JohanvdWest** [happner/happn#20]
If you set with a merge and the new object has a property with value 0 or false, then that property will be overwritten by the old data.

service.js line 336 should be:
```
                if (setData.data[propertyName] == null)
```

**Comment by southbite** [comment]
ahhh - how silly - so any falsey property is overwritten - ok, should I fix this and release to 0.0.45-auth?

**Comment by JohanvdWest** [comment]
Maybe we should do it on the current master so that we can get it out as
soon as possible.

**Comment by nomilous** [comment]
I just merged the fix for bug https://github.com/happner/happner/issues/49 into master to be included. 

Tiny change.

**Comment by southbite** [comment]
Fixed - release 2.1.5
