### ISSUE TITLE
Happn client initialisation peculiarities.

### ISSUE THREAD

**Issue by nomilous** [happner/happn#7]
Initialization is a strange combination of class instantiation (new) with callback and .initialize(). I lean toward the simplicity of core modules that use the network.   e.g http.createServer(opts, cb)  .createClient()

**Comment by southbite** [comment]
you can now initialize very simply - using promises:

var happn = require('../lib/index');
var service = happn.service;

 service.create()

      .then(function (happnInst) {
        happnInstance = happnInst;
        callback();
      })

      .catch(callback)

      ;
